"""ROOT InVEST Plugin."""

import logging

from natcap.invest import validation

# from . import __version__
from .model_spec import MODEL_SPEC
from . import rootcore
from . import preprocessing
from . import postprocessing
from . import optimization

LOGGER = logging.getLogger(__name__)


class RootInputError(Exception):
    pass


def execute(args):
    """
    Main entry point for the plugin.

    Converts the arguments from the UI to the format expected by the internal code and calls
    preprocessing/optimization sub-models as requested.

    Args:
        args: a dictionary in the form generated by the InVEST Workbench matching arguments
        specified by `MODEL_SPEC`.
    
    Returns:
        registry: a dictionary linking output file keys to file paths

    """
    # LOGGER.info(f'Running ROOT version {__version__}')
    args, file_registry, task_graph = MODEL_SPEC.setup(args)
    internal_args = rootcore.parse_args(args)

    if args['do_preprocessing']:
        print('doing pre-processing')
        preprocessing.execute(internal_args)
    else:
        print('skipping pre-processing')

    if args['do_optimization']:
        print('doing optimization')
        optimization.execute(internal_args)
        postprocessing.execute(internal_args)
    else:
        print('skipping optimization')

    return file_registry.registry


@validation.invest_validator
def validate(args):
    return validation.validate(args, MODEL_SPEC)
